# Workflow derived from https://github.com/rstudio/shiny-workflows
#
# NOTE: This Shiny team GHA workflow is overkill for most R packages.
# For most R packages it is better to use https://github.com/r-lib/actions
on:
  push:
    branches: [main, rc-**]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 9 * * 1" # every monday

name: Package checks

jobs:
  website:
    uses: rstudio/shiny-workflows/.github/workflows/website.yaml@v1
  routine:
    uses: rstudio/shiny-workflows/.github/workflows/routine.yaml@v1
  R-CMD-check:
    uses: rstudio/shiny-workflows/.github/workflows/R-CMD-check.yaml@v1

  # quarto:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out repository
  #       uses: actions/checkout@v3

  #     # TODO-barret: document this process in the readme:
  #     # TODO-barret-future; Install R, r-shinylive
  #     # TODO-barret-future; Install posit-dev/shinylive; Run `make submodules all`; Then `make build-prod-r`;
  #     # TODO-barret-future; r-shinylive: link local copy
  #     # TODO-barret-future; Render quarto project

  #     - name: Set up Quarto
  #       uses: quarto-dev/quarto-actions/setup@v2

  #     - name: Render Quarto Project
  #       uses: quarto-dev/quarto-actions/render@v2
  #       with:
  #         path: local/quarto/r.qmd
  #     # TODO-barret-future; Test the output of the render
